# Generated by Django 3.0.2 on 2020-02-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='userID',
        ),
        migrations.AddField(
            model_name='bet',
            name='betOutcome',
            field=models.CharField(choices=[(0, ''), (1, '<django.db.models.fields.related.ForeignKey>Wins'), (1, '<django.db.models.fields.related.ForeignKey>Wins')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='bet',
            name='betteeID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party2', to='bets.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='bettorID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='party1', to='bets.User'),
            preserve_default=False,
        ),
    ]
