# Generated by Django 3.0.2 on 2020-02-17 18:53

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20200216_2105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bet',
            managers=[
                ('bets', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
