# Generated by Django 3.0.2 on 2020-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20200217_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='betOutcome',
            field=models.CharField(choices=[('0', ''), ('1', '<django.db.models.fields.related.ForeignKey>Wins'), ('2', '<django.db.models.fields.related.ForeignKey>Wins')], default='0', max_length=20),
        ),
    ]
