# Generated by Django 3.0.2 on 2020-03-09 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0005_auto_20200217_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=30)),
                ('assets', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['betID']},
        ),
        migrations.AlterModelManagers(
            name='bet',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='betteeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='bettorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
