# Generated by Django 3.0.2 on 2020-03-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20200309_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='assets',
            new_name='account_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastName',
        ),
    ]
