# Generated by Django 3.0.2 on 2020-03-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_auto_20200315_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='betID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
