# Generated by Django 3.0.2 on 2020-03-28 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0008_auto_20200328_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='betteeID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='party2', to=settings.AUTH_USER_MODEL),
        ),
    ]
