# Generated by Django 3.0.2 on 2020-03-29 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bets', '0009_auto_20200328_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='betteeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party2', to=settings.AUTH_USER_MODEL),
        ),
    ]
